spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL}
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.default_batch_fetch_size: 1000
  jackson:
    property-naming-strategy: SNAKE_CASE
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  servlet:
    context-path: /api/v1

auth:
  jwt:
    secret: ${JWT_SECRET}
    prefix: ${JWT_PREFIX}
    header: ${JWT_HEADER}
    exp:
      access: ${JWT_EXP_ACCESS}
      refresh: ${JWT_EXP_REFRESH}
      document: ${JWT_EXP_DOCUMENT}

cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCESS_KEY}
      secretKey: ${AWS_SECRET_KEY}
    region: ${AWS_REGION}
    s3:
      bucket: ${AWS_S3_BUCKET_NAME}
