spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL}
  jpa:
    hibernate:
      ddl-auto: update
  jackson:
    property-naming-strategy: SNAKE_CASE

auth:
  jwt:
    secret: ${JWT_SECRET}
    exp: ${JWT_EXP}
    prefix: ${JWT_PREFIX}
    header: ${JWT_HEADER}
